#ifndef DEFINES_HLSLI
#define DEFINES_HLSLI


#define ROW_MAT row_major matrix

// ConstantBuffer Register Num
#define BUFFER_NUM_GLOBAL b0
#define BUFFER_NUM_TRANSFORM b1
#define BUFFER_NUM_DIRECTIONAL_LIGHT b2
#define BUFFER_NUM_SPOT_LIGHT b3
#define BUFFER_NUM_POINT_LIGHT b4
#define BUFFER_NUM_MATERIAL b5
#define BUFFER_NUM_BONE b6
#define BUFFER_NUM_BONEINDEX b7

#define MAX_DIRECTIONAL_LIGHT_COUNT 1
#define MAX_SPOT_LIGHT_COUNT 3
#define MAX_POINT_LIGHT_COUNT 3

#endif /* DEFINES_HLSLI */